#!/bin/bash

# install touch.calib to /etc
sudo install -o root -g root -m 777 touch.calib /etc
# install shared library to proper location
sudo install -o root -g root -m 777 src/xfdrvtouch_drv.so /usr/lib/xorg/modules/input
# install xorg.conf to /etc/X11
sudo install -o root -g root -m 777 xorg.conf /etc/X11
echo Installation complete!

exit
